import crypto from "node:crypto";
import bcrypt from "bcryptjs";
import type Database from "better-sqlite3";

/**
 * The first account on a database that has none.
 *
 * Without this a fresh deployment has no way in: registration needs an invite
 * code, invite codes are generated by a script on the host, and the admin
 * pages need an entry in `CDB_ADMIN_EMAILS` that a new operator has no reason
 * to know about. The image is published for other people to run, so "works
 * only if you already know the two undocumented steps" is a defect.
 *
 * The password is NOT a fixed default. A published image with admin/admin on
 * a public URL is the single most scanned-for weakness there is, and this app
 * is reachable from the internet by design. So:
 *
 *   · `CDB_ADMIN_PASSWORD` set  → that password, and nothing is printed.
 *   · unset                     → a random one, printed once to the container
 *                                 log, where the operator who just started it
 *                                 is already looking.
 *
 * Runs only when the users table is empty, so it can never overwrite a real
 * account, and never fires on an existing install (including the e2e fixture,
 * which seeds its own user before the server starts).
 */

const EMAIL = "admin@localhost";

export function bootstrapAdmin(db: Database.Database): void {
  if (process.env.CDB_BOOTSTRAP_ADMIN === "off") return;
  const existing = db
    .prepare("SELECT COUNT(*) AS n FROM user.users")
    .get() as { n: number };
  if (existing.n > 0) return;

  const configured = process.env.CDB_ADMIN_PASSWORD?.trim();
  const password = configured || crypto.randomBytes(12).toString("base64url");
  db.prepare(
    `INSERT INTO user.users (id, email, password_hash, display_name, is_admin)
     VALUES (?, ?, ?, 'admin', 1)`,
  ).run(crypto.randomUUID(), EMAIL, bcrypt.hashSync(password, 12));

  if (configured) {
    console.log(`[bootstrap] 已创建管理员 ${EMAIL},密码取自 CDB_ADMIN_PASSWORD`);
    return;
  }
  // Printed as a block because it is the one line in the log that has to be
  // read, and it is never printed again.
  console.log(
    [
      "",
      "  ┌─────────────────────────────────────────────",
      "  │ 已创建管理员账号(仅此一次)",
      `  │   邮箱:${EMAIL}`,
      `  │   密码:${password}`,
      "  │ 登录后请在 账号 页面修改密码。",
      "  └─────────────────────────────────────────────",
      "",
    ].join("\n"),
  );
}
